### ISSUE TITLE
部分版本chrome浏览器没有设置按钮

### ISSUE THREAD

**Issue by Luckyqiao** [ververcpp/ChaZD#10]
我有两台电脑，其中一台上的chaZD的设置按钮存在，另外一个却没有。如图
![1](https://cloud.githubusercontent.com/assets/5688532/9388839/89c17792-479a-11e5-9e23-4ba8f4e61562.png)

chrome的版本是
![2](https://cloud.githubusercontent.com/assets/5688532/9388850/975e50a0-479a-11e5-847f-971ae735d01c.png)

chaZD已经更新到最新版。

**Comment by ververcpp** [comment]
可能是因为你的 chrome 是英文版本的原因，具体的解决方法如下（我在 readme 中也有注释）：
非中文版Chrome浏览器的用户，如出现插件弹出窗口字体无法正常显示的情况，麻烦请更改浏览器的最小字号为12px （具体步骤: settings-->show advanced settings-->Web content中的Customize fonts... -->Minimum font size将最小字号改为12px）。
