### ISSUE TITLE
能不能做个独立的图标放在chrome://apps/

### ISSUE THREAD

**Issue by qwIvan** [ververcpp/ChaZD#15]
这么做在浏览器没打开的时候也可以用了

**Comment by greatghoul** [comment]
如果发有独立图标放在 apps 里面那就是个 app 而不是个插件，这两个不能并存的。

**Comment by ververcpp** [comment]
应用和插件应该是两个独立的程序，ChaZD的使用场景只能局限在浏览器内。我猜测你想要的使用场景类似于客户端的查词软件，比如金山词霸，如果是这样的话，我还是建议你用那些比较成熟的客户端软件吧，应该比 ChaZD 要好用的多。

**Comment by qwIvan** [comment]
还是觉得chaDZ比较方便
Linux下的有道并不好用
