### ISSUE TITLE
最近字典查询有点不正常

### ISSUE THREAD

**Issue by a1exlism** [ververcpp/ChaZD#29]
版本: 49.0.2623.75 (正式版本) beta （64 位）
系统:Ubuntu 15.04 vivid
开关https接口都一样,差不多一周时间了...请问是个人问题么??

**Comment by a1exlism** [comment]
重新测试了一下,似乎时移动网络的锅,换了闪讯和4g热点就正常了..

**Comment by ververcpp** [comment]
这个不是你的个人问题，最近有道开始封禁使用频率过高的接口，所以会出现不定时无法使用的情况。我将版本临时更新到了0.8.20.3，随机使用3个接口 key，能稍微缓解下封禁的问题。

**Comment by a1exlism** [comment]
赶紧升级了插件，找遍chrome也没发现可替代的，希望作者继续加油，感谢:)
