### ISSUE TITLE
能不能用https请求有道api？

### ISSUE THREAD

**Issue by qwIvan** [ververcpp/ChaZD#3]
如果用http请求有道api的话，在HTTPS的网站下查单词，会让chrome地址栏左侧的绿色锁图案变成黄色。绿色代表纯https，黄色代表https混点http，而混进来的http正是有道的api。

**Comment by ververcpp** [comment]
我刚更新了 0.8.9 版本，已经改用 https 协议。如有什么问题欢迎继续反馈 :smile:
