### ISSUE TITLE
能自定义有道词典key的版本是哪个版本呢？

### ISSUE THREAD

**Issue by Finb** [ververcpp/ChaZD#38]
非常感谢你写的这个非常好用的扩展！

由于有道词典会频繁，我想换成自己的key。查阅Issues 后发现你说会支持自定义，但是我能下载的版本都找不到自定义的入口，所以想问一下这个能自定义的版本是否有上线？

**Comment by Finb** [comment]
已自行打包解决

**Comment by ververcpp** [comment]
抱歉，目前新版本还未上线，在下个版本中会提供显式的自定义接口。
