### ISSUE TITLE
能不能像transit那样加入按住shift键，对链接中的单词进行划词？

### ISSUE THREAD

**Issue by qwIvan** [ververcpp/ChaZD#4]

**Comment by ververcpp** [comment]
目前 ChaZD已经支持这个功能，在设置里面开启这个选项就可以了。
![image](https://cloud.githubusercontent.com/assets/980232/8643148/3a9169d0-2962-11e5-905f-4efd1e51bb05.png)

**Comment by qwIvan** [comment]
!!!
早说。。。才发现。
