### ISSUE TITLE
想在上面输入框，输入单词的时候实时响应。

### ISSUE THREAD

**Issue by qwIvan** [ververcpp/ChaZD#5]
之前复制粘贴上去查询的时候，都是手动按Enter。
刚刚才发现输入框左边有个放大镜可以查询，不需要按键盘。
如果实时响应，就不需要手动搜索了。
如果能找到API的话，像有道、Google那样做个输入建议更好。

我最近也在学前端。

**Comment by ververcpp** [comment]
根据你的使用方式，我可能需要改进的是当在输入框中输入（或通过复制粘贴）了一个单词后，如果在0.5 ~ 1s内没有再输入的话就直接返回查词结果。不知道这个是不是你想象的使用场景。这个功能我会暂时加入下个版本的更新计划，等测试一下具体的使用效果后再决定是否添加这个功能。
关于输入建议，单纯靠 api 恐怕还不行，可能需要字典文件的相关支持才能实现。我的想法是插件的使用场景可能大部分是划词，其次是在图标输入框中输入所在页面中的单词（这也可以当做是输入提示），不像在有道那种单独的网页中进行查词。所谓术业有专攻嘛，过于冗余的功能可能有伪插件简洁易用的初衷，所以暂时就不考虑加入输入建议这个功能了。

**Comment by qwIvan** [comment]
因为我平时查单词都是用你的插件查的，所以如果有输入建议的话还是挺方便的，可能其他人不会这么做，那不考虑了。
第一点实时响应还是有必要的。

**Comment by ververcpp** [comment]
我刚更新了新版本，已经支持实时响应的功能，如果在使用中有什么问题欢迎反馈。

**Comment by qwIvan** [comment]
嗯，很棒。我不理解的是为什么要延时响应呢？

**Comment by ververcpp** [comment]
我设定的延时时间是0.5秒，因为我觉得如果做到完全的实时响应，在你每敲入一个字母时都会发出一个查询请求，这是没有必要的。延时0.5秒对使用效果的影响应该不是很大，至少我是这么觉得。

**Comment by greatghoul** [comment]
实时响应很费请求次数吧，两下就超限了。

**Comment by qwIvan** [comment]
原来有道API，请求频率限制为每小时1000次，超过限制会被封禁。
如果我用自己的API key，应该够用吧。

**Comment by greatghoul** [comment]
自己的肯定就够用了，不过应该需要作者给你放个能定制 API Key 的地方，或者你自己直接安装开发版就好了，都可以自己改。

**Comment by ververcpp** [comment]
目前用户数还不多，还没有遇到超限封禁的情况，不过我最近会考虑给有道发个邮件，看看能不能放宽限制。定制 API Key 这种功能可能暂时不会考虑，因为随着用户增多，对此有需求或是能自己搞定的人还是少数，加入太多大部分人看不懂的功能反而会影响用户体验。有需求的朋友就请自行下载源码，在 utility.js 中修改 key 即可。

**Comment by ververcpp** [comment]
@greatghoul 对了，请教一下 transit 有遇到过超限的问题吗，你们是怎么解决的？

**Comment by greatghoul** [comment]
@ververcpp 没有，或者用户遇到了，没有报给我，transit 的用户也并不多。
