### ISSUE TITLE
开启shift超链接功能后，导致shift网页文本选择失效，建议是否同时加个ctrl组合键（e.keyCode == 16 && e.ctrlKey）

### ISSUE THREAD

**Issue by ststring** [ververcpp/ChaZD#6]
开启shift超链接功能后，导致shift网页文本选择失效（请参照excel中shift选择多行功能）

建议修改：
if(e.keyCode == 16 && e.ctrlKey){
       submit();
}

**Comment by ververcpp** [comment]
新版本0.8.11已经修改了这个 bug，如果使用中有什么问题欢迎继续反馈。

关于图标，因为本人确实不太擅长图标设计，一直有换图标的打算，可是迟迟不知该怎么下手。近期我会尽力重新设计一个好看一点的图标。感谢你的支持！
