### ISSUE TITLE
完善ChaZD，支持有道智云api 

### ISSUE THREAD

**Issue by codethereforam** [ververcpp/ChaZD#63]
请参考博客“[完善chrome翻译插件ChaZD，支持有道智云api](https://codethereforam.github.io/2017-12-31-ChaZD-youdao/)”或[https://github.com/codethereforam/ChaZD](https://github.com/codethereforam/ChaZD)

**Comment by Justsoos** [comment]
https://github.com/codethereforam/ChaZD  正在用这个升级版本，但有不少问题。
经常刷不出来翻译结果，显示网络问题？还有 chrome 里鼠标划词经常出不来翻译窗口。
由于那边没有 issues 反馈页面，就写到这里了。

**Comment by codethereforam** [comment]
@Justsoos  谢谢反馈bug，我已在我项目里开了issues。我最近一直在用我项目master分支的这个插件，我的系统是ubuntu，并没有出现过你提到的bug，刚才我用win10测试了一下也没有问题。如果有问题，请到我项目issues提出并指出你的系统环境 ，chrome版本以及你用的是我哪次commit的版本（指出commit日期）。
