### ISSUE TITLE
Feature Request：翻译结果自动隐藏

### ISSUE THREAD

**Issue by Hs-Yeah** [ververcpp/ChaZD#8]
如果能像 TransIt 那样在一定时间后自动隐藏翻译结果，并提供设置项来由用户决定划词翻译结果显示时长，那就好了 :smiley:

**Comment by ververcpp** [comment]
其实当初写这个插件时，我是故意没有加入这个功能，因为当时觉得这个功能很不符合我个人的使用习惯。不过我会考虑后续加入这个功能，暂时计划是用户既可以通过鼠标单击隐藏翻译结果，也可以在特定时间后自动隐藏。

**Comment by Hs-Yeah** [comment]
嗯，可以加入选项，让用户决定是否需要自动隐藏，如果需要自动隐藏，就再设定自动隐藏的时间。

**Comment by ververcpp** [comment]
新版本0.8.12已经支持了自动隐藏的功能，在设置里面可以选择开启或关闭该功能，欢迎试用。如有什么问题，欢迎及时反馈。

**Comment by Hs-Yeah** [comment]
太赞了！感谢您做出了这么好的扩展~

**Comment by greatghoul** [comment]
:+1:
