### ISSUE TITLE
要是能加个禁用插件的功能就好了

### ISSUE THREAD

**Issue by Luckyqiao** [ververcpp/ChaZD#9]
有时不想用的时候，会造成很多干扰，却不知道要怎么关掉。

**Comment by ververcpp** [comment]
在设置里面可以选择关闭划词功能，设置按钮在弹出窗口的左下角的齿轮图标。

**Comment by Luckyqiao** [comment]
原来还有这个高级的功能，竟然一直没有发现

**Comment by ververcpp** [comment]
没有发现的应该不只你一个人，我看到一些反馈都希望加入关闭划词的功能，可是它一直就在那里啊 :sweat: 之前的为了界面美观，故意把设置按钮的颜色弄的不是很明显，看来是错了，新版本我加深了按钮的颜色，后续版本我争取弄一个独立的选项页面出来。
